-- Tabela USR (Usuários)
CREATE TABLE USR (
  ID_USR_USER          NUMBER                       CONSTRAINT PK_USR PRIMARY KEY,
  CD_USR_EMAIL         VARCHAR2(255)                CONSTRAINT UK_USR_EMAIL UNIQUE,
  TX_USR_PASSWORD_HASH VARCHAR2(255)                NOT NULL,
  DH_USR_CREATED_AT    TIMESTAMP WITH TIME ZONE
);

-- Tabela ALT (Alertas)
CREATE TABLE ALT (
  ID_ALT_ALERT         NUMBER                       CONSTRAINT PK_ALT PRIMARY KEY,
  ID_USR_USER          NUMBER                       NOT NULL,
  TP_ALT_TYPE          VARCHAR2(50),
  NR_ALT_LEVEL         NUMBER,
  DH_ALT_CREATED_AT    TIMESTAMP WITH TIME ZONE,
  MD_ALT_LAT           NUMBER,
  MD_ALT_LNG           NUMBER,
  CONSTRAINT FK_ALT_USR FOREIGN KEY (ID_USR_USER) REFERENCES USR (ID_USR_USER)
);

-- Tabela SHL (Abrigos)
CREATE TABLE SHL (
  ID_SHL_SHELTER       NUMBER                       CONSTRAINT PK_SHL PRIMARY KEY,
  NM_SHL_NAME          VARCHAR2(150),
  MD_SHL_LAT           NUMBER                       NOT NULL,
  MD_SHL_LNG           NUMBER                       NOT NULL,
  QT_SHL_CAPACITY      NUMBER,
  QT_SHL_AVAILABLE     NUMBER
);

-- Tabela CLI (Itens de Checklist)
CREATE TABLE CLI (
  ID_CLI_ITEM          NUMBER                       CONSTRAINT PK_CLI PRIMARY KEY,
  ID_USR_USER          NUMBER                       NOT NULL,
  NM_CLI_LABEL         VARCHAR2(100),
  ST_CLI_STATUS        CHAR(1)                      CONSTRAINT CK_CLI_STATUS CHECK (ST_CLI_STATUS IN ('P','C')),
  DH_CLI_UPDATED_AT    TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_CLI_USR FOREIGN KEY (ID_USR_USER) REFERENCES USR (ID_USR_USER)
);

-- Tabela CSS (Sessões de Chat)
CREATE TABLE CSS (
  ID_CSS_SESSION       NUMBER                       CONSTRAINT PK_CSS PRIMARY KEY,
  ID_USR_USER          NUMBER                       NOT NULL,
  DH_CSS_STARTED_AT    TIMESTAMP WITH TIME ZONE,
  DH_CSS_ENDED_AT      TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_CSS_USR FOREIGN KEY (ID_USR_USER) REFERENCES USR (ID_USR_USER)
);

-- Tabela CMT (Mensagens de Chat)
CREATE TABLE CMT (
  ID_CMT_MESSAGE       NUMBER                       CONSTRAINT PK_CMT PRIMARY KEY,
  ID_CSS_SESSION       NUMBER                       NOT NULL,
  TP_CMT_SENDER        VARCHAR2(20)                 CONSTRAINT CK_CMT_SENDER CHECK (TP_CMT_SENDER IN ('USER','BOT','PSY')),
  TX_CMT_TEXT          CLOB,
  DH_CMT_SENT_AT       TIMESTAMP WITH TIME ZONE,
  CONSTRAINT FK_CMT_CSS FOREIGN KEY (ID_CSS_SESSION) REFERENCES CSS (ID_CSS_SESSION)
);

-- Índices adicionais
-- Índice composto para filtrar itens pendentes rapidamente
CREATE INDEX IDX_CLI_USER_STATUS
  ON CLI (ID_USR_USER, ST_CLI_STATUS);

-- Índices geoespaciais (Oracle Spatial)
CREATE INDEX IDX_SHL_SPATIAL
  ON SHL (MD_SHL_LAT, MD_SHL_LNG)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX IDX_ALT_SPATIAL
  ON ALT (MD_ALT_LAT, MD_ALT_LNG)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX;
